### ISSUE TITLE
SimException when using 'proguard-android-optimize.txt'

### ISSUE THREAD

**Issue by ddsakura** [StraaS/StraaS-android-sdk-sample#48]
Hi,

SDK v0.5.2
When I use proguard-android-optimize.txt to proguard app
in build process
will met "Compile with Proguard gives SimException: “local variable type mismatch”" error

When I use proguard-android.txt to proguard app
I can build app successfully
but when I start live 
will met init fail io.straas.android.sdk.base.credential.a$c: error

please provide correct proguard info for sdk,

Thank you

**Comment by b95505017** [comment]
Hi Sakura,

Thanks for filing this issue, we'll check ASAP.

**Comment by b95505017** [comment]
Hi @ddsakura 
I don't meet any issue when using `proguard-android.txt` to build & run our sample app.
